In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import time 

import warnings
warnings.filterwarnings('ignore')

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity='all'

In [2]:
#Reading CSV File
data = pd.read_csv('F:\JOBSEARCH\Datasets\Kaggle Dataset Cat in Dat\cattrain.csv')
data.columns

Index(['id', 'bin_0', 'bin_1', 'bin_2', 'bin_3', 'bin_4', 'nom_0', 'nom_1',
       'nom_2', 'nom_3', 'nom_4', 'nom_5', 'nom_6', 'nom_7', 'nom_8', 'nom_9',
       'ord_0', 'ord_1', 'ord_2', 'ord_3', 'ord_4', 'ord_5', 'day', 'month',
       'target'],
      dtype='object')

In [3]:
#Know your Dataset
data.head()

id  bin_0  bin_1  bin_2 bin_3 bin_4  nom_0      nom_1    nom_2    nom_3  \
0   0      0      0      0     T     Y  Green   Triangle    Snake  Finland   
1   1      0      1      0     T     Y  Green  Trapezoid  Hamster   Russia   
2   2      0      0      0     F     Y   Blue  Trapezoid     Lion   Russia   
3   3      0      1      0     F     Y    Red  Trapezoid    Snake   Canada   
4   4      0      0      0     F     N    Red  Trapezoid     Lion   Canada   

   ...      nom_9 ord_0        ord_1        ord_2 ord_3 ord_4  ord_5 day  \
0  ...  2f4cb3d51     2  Grandmaster         Cold     h     D     kr   2   
1  ...  f83c56c21     1  Grandmaster          Hot     a     A     bF   7   
2  ...  ae6800dd0     1       Expert     Lava Hot     h     R     Jc   7   
3  ...  8270f0d71     1  Grandmaster  Boiling Hot     i     D     kW   2   
4  ...  b164b72a7     1  Grandmaster     Freezing     a     R     qP   7   

  month target  
0     2      0  
1     8      0  
2     2      0  
3     1      1  
4     8      0  

[5 rows x 25 columns]

In [4]:
#check for null values
data.isnull().sum()

id        0
bin_0     0
bin_1     0
bin_2     0
bin_3     0
bin_4     0
nom_0     0
nom_1     0
nom_2     0
nom_3     0
nom_4     0
nom_5     0
nom_6     0
nom_7     0
nom_8     0
nom_9     0
ord_0     0
ord_1     0
ord_2     0
ord_3     0
ord_4     0
ord_5     0
day       0
month     0
target    0
dtype: int64

In [5]:
#get all columns data 
data.columns

Index(['id', 'bin_0', 'bin_1', 'bin_2', 'bin_3', 'bin_4', 'nom_0', 'nom_1',
       'nom_2', 'nom_3', 'nom_4', 'nom_5', 'nom_6', 'nom_7', 'nom_8', 'nom_9',
       'ord_0', 'ord_1', 'ord_2', 'ord_3', 'ord_4', 'ord_5', 'day', 'month',
       'target'],
      dtype='object')

In [6]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [7]:
df = data

In [8]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['ord_0']  = label_encoder.fit_transform(df['ord_0'])
df['ord_1']  = label_encoder.fit_transform(df['ord_1'])
df['ord_2']  = label_encoder.fit_transform(df['ord_2'])
df['ord_3']  = label_encoder.fit_transform(df['ord_3'])
df['ord_4']  = label_encoder.fit_transform(df['ord_4'])
df['ord_5']  = label_encoder.fit_transform(df['ord_5'])
df['bin_0']  = label_encoder.fit_transform(df['bin_0'])
df['bin_1']  = label_encoder.fit_transform(df['bin_1'])
df['bin_2']  = label_encoder.fit_transform(df['bin_2'])
df['bin_3']  = label_encoder.fit_transform(df['bin_3'])
df['bin_4']  = label_encoder.fit_transform(df['bin_4'])
df['nom_0']  = label_encoder.fit_transform(df['nom_0'])
df['nom_1']  = label_encoder.fit_transform(df['nom_1'])
df['nom_2']  = label_encoder.fit_transform(df['nom_2'])
df['nom_3']  = label_encoder.fit_transform(df['nom_3'])
df['nom_4']  = label_encoder.fit_transform(df['nom_4'])
df['nom_5']  = label_encoder.fit_transform(df['nom_5'])
df['nom_6']  = label_encoder.fit_transform(df['nom_6'])
df['nom_7']  = label_encoder.fit_transform(df['nom_7'])
df['nom_8']  = label_encoder.fit_transform(df['nom_8'])
df['nom_9']  = label_encoder.fit_transform(df['nom_9'])

In [9]:
from sklearn.model_selection import train_test_split
X = df.drop(('target'),axis=1)
y = df.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=101)

In [10]:
from sklearn.linear_model import LogisticRegression
ln = LogisticRegression()
ln.fit(X_train,y_train)
pred = ln.predict(X_test)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [11]:
from sklearn.metrics import confusion_matrix , classification_report , accuracy_score
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print(accuracy_score(y_test,pred))

[[50934  1008]
 [22315   743]]
              precision    recall  f1-score   support

           0       0.70      0.98      0.81     51942
           1       0.42      0.03      0.06     23058

    accuracy                           0.69     75000
   macro avg       0.56      0.51      0.44     75000
weighted avg       0.61      0.69      0.58     75000

0.6890266666666667


In [12]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train,y_train)
pred = rfc.predict(X_test)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [13]:
from sklearn.metrics import confusion_matrix , classification_report , accuracy_score
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print(accuracy_score(y_test,pred))

[[48740  3202]
 [17149  5909]]
              precision    recall  f1-score   support

           0       0.74      0.94      0.83     51942
           1       0.65      0.26      0.37     23058

    accuracy                           0.73     75000
   macro avg       0.69      0.60      0.60     75000
weighted avg       0.71      0.73      0.69     75000

0.7286533333333334


In [14]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)
pred = dtree.predict(X_test)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [15]:
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print(accuracy_score(y_test,pred))

[[37586 14356]
 [13315  9743]]
              precision    recall  f1-score   support

           0       0.74      0.72      0.73     51942
           1       0.40      0.42      0.41     23058

    accuracy                           0.63     75000
   macro avg       0.57      0.57      0.57     75000
weighted avg       0.64      0.63      0.63     75000

0.6310533333333334


In [16]:
!pip install xgboost

You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [17]:
from xgboost import XGBClassifier

In [18]:
model = XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [19]:
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]

In [20]:
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 74.45%


In [21]:
import pickle
model = XGBClassifier()
model.fit(X_train, y_train)
filename = 'Final_Model.sav'
pickle.dump(model, open(filename, 'wb'))

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [22]:
final_predict = pd.read_csv('test.csv')

In [23]:
df = final_predict

In [24]:

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['ord_0']  = label_encoder.fit_transform(df['ord_0'])
df['ord_1']  = label_encoder.fit_transform(df['ord_1'])
df['ord_2']  = label_encoder.fit_transform(df['ord_2'])
df['ord_3']  = label_encoder.fit_transform(df['ord_3'])
df['ord_4']  = label_encoder.fit_transform(df['ord_4'])
df['ord_5']  = label_encoder.fit_transform(df['ord_5'])
df['bin_0']  = label_encoder.fit_transform(df['bin_0'])
df['bin_1']  = label_encoder.fit_transform(df['bin_1'])
df['bin_2']  = label_encoder.fit_transform(df['bin_2'])
df['bin_3']  = label_encoder.fit_transform(df['bin_3'])
df['bin_4']  = label_encoder.fit_transform(df['bin_4'])
df['nom_0']  = label_encoder.fit_transform(df['nom_0'])
df['nom_1']  = label_encoder.fit_transform(df['nom_1'])
df['nom_2']  = label_encoder.fit_transform(df['nom_2'])
df['nom_3']  = label_encoder.fit_transform(df['nom_3'])
df['nom_4']  = label_encoder.fit_transform(df['nom_4'])
df['nom_5']  = label_encoder.fit_transform(df['nom_5'])
df['nom_6']  = label_encoder.fit_transform(df['nom_6'])
df['nom_7']  = label_encoder.fit_transform(df['nom_7'])
df['nom_8']  = label_encoder.fit_transform(df['nom_8'])
df['nom_9']  = label_encoder.fit_transform(df['nom_9'])

In [52]:
# Load model from disk and use it to make new predictions
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)
print(result)

# Load test dataset
final_predict = df
X_train = final_predict
pred = loaded_model.predict(X_train)
final_Output = pd.DataFrame(pred)

0.7445466666666667


In [49]:
final_Output.to_csv('file1.csv',columns=None)

In [50]:
final_Output

0
0       0
1       1
2       0
3       1
4       1
...    ..
199995  0
199996  0
199997  0
199998  0
199999  0

[200000 rows x 1 columns]